import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [query, setQuery] = useState('');

  const router = useRouter();

  const onSearch = async (e) => {
    e.preventDefault();
    router.push(`/search/${query}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <form>
          <input value={query} onChange={(e) => setQuery(e.target.value)} />

          <button onClick={onSearch} type='submit'>
            Search
          </button>
        </form>
      </main>
    </div>
  );
}
